import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Template: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>Title</h1>
    </div>
  );
};

export default Template;
