import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Sanctuary Internal tools</h1>

      <ul className={styles.menu}>
        <li>
          <Link href="/get-mint-list">
            <a>Get Mint List</a>
          </Link>
        </li>
        <li>
          <Link href="/get-candy-machine-id">
            <a>Get Candy Machine ID</a>
          </Link>
        </li>
        <li>
          <Link href="/get-mint-list">
            <a>Get Mint List</a>
          </Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
